exclude: >
    (?x)(
        LICENSE$|
        \.snap$|
        \.map$|
        \.map\.js$|
        ^tests/sentry/lang/.*/fixtures/|
        ^tests/fixtures/|
        ^src/sentry/static/sentry/vendor/|
        ^tests/sentry/lang/javascript/example-project/|
        ^src/.*/locale/|
        ^src/sentry/data/
    )
repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    - id: flake8
      types: [python]
      language_version: 'python2.7'
      log_file: '.artifacts/flake8.pycodestyle.log'
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      types: [python]
      exclude: (south_migrations/)
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-symlinks
    - id: end-of-file-fixer
      exclude_types: [svg]
    - id: trailing-whitespace
      exclude_types: [svg]
    - id: debug-statements
    - id: requirements-txt-fixer
# -   repo: git://github.com/getsentry/pre-commit-hooks
#     rev: f3237d2d65af81d435c49dee3593dc8f03d23c2d
#     hooks:
#     - id: prettier
#     - id: eslint
#       args: ['--format=checkstyle']
#       log_file: '.artifacts/eslint.checkstyle.xml'
